const Constants = {
    RECIPES_FETCHING: 'RECIPES_FETCHING',
    RECIPES_RECEIVED: 'RECIPES_RECEIVED',
    RECIPE_FETCHING: 'RECIPE_FETCHING',
    RECIPE_RECEIVED: 'RECIPE_RECEIVED',
};

export default Constants;
